spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=gobika@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
razorpay.key.id=rzp_test_TW1YETpnupFDFL
razorpay.key.secret=EviBarq196B0NKlIQHZ26mda